version: "2"
services:
  web:
    build: "."
    command: mix phoenix.server
    volumes:
      - .:/app
    depends_on:
      - db
    working_dir: /app
    ports:
      - "4000:4000"

  db:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: elixir_phoenix_elm_boilerplate_dev
    ports:
      - "5432:5432"
